name: Pull Request Pre-Flight Checks
on:
  pull_request:
    paths:
      - "terraform/**"
      - "examples/**"
      - ".github/workflows/pull_request.yaml"
jobs:
  validate:
    name: Validate pull request contents
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        folder:
          - terraform/
          - example/single-node
          - example/worker-group
    steps:
      - name: Setup Terraform linter
        uses: terraform-linters/setup-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Terraform lint
        shell: bash
        run: tflint -f compact
        working-directory: ${{ matrix.folder }}
      - name: Terraform format check
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.folder }}
      
